### ISSUE TITLE
Have a PPA for Sauna

### ISSUE THREAD

**Issue by mfaure** [NicolasLM/sauna#66]
Sauna is extremely useful for monitoring hosts with OVH Shinken as a Service. It is installed on each host or VM that is monitored. 

If installing it is easy thanks to the .deb, upgrading it on each and every monitored host is a real pain.

Would it be possible to offer a PPA (Personal Package Archive) for Sauna ? (so that upgrades would be done automatically)

**Comment by NicolasLM** [comment]
I tried but the whole launchpad thing is far from user friendly and seems very outdated.
Moreover I couldn't find information on how to hook it to Github and/or PyPI to avoid manual steps.

I'm going to close this issue, however anyone with more experience on the process of publishing to a PPA should feel free to create its own and include it in the docs.
