### ISSUE TITLE
Add headers and payload support in HTTP and HTTP-JSON plugin

### ISSUE THREAD

**Issue by xavierhardy** [NicolasLM/sauna#68]
Judging by the code, I don't see the possibility to set the headers and the payload/body in HTTP and HTTP-JSON plugins.

**Comment by NicolasLM** [comment]
Hi Xavier!

You're right, this is not currently possible. The feature should be easy to implement though.

Feel free to submit a PR, otherwise I will tackle that later.

**Comment by xavierhardy** [comment]
OK, I'll do it.

**Comment by xavierhardy** [comment]
Pull request #70
